# Generated by Django 4.1.1 on 2022-09-26 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=30)),
                ('ingredientes', models.TextField()),
                ('modo_de_preparo', models.TextField()),
                ('tempo_de_preparo', models.IntegerField()),
                ('rendimento', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=30)),
                ('data_receita', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
